# Generated by Django 4.2.6 on 2024-04-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Author', models.CharField(max_length=200)),
                ('Price', models.FloatField()),
                ('Stock', models.IntegerField()),
                ('Image', models.CharField(max_length=2083)),
                ('Pages', models.IntegerField()),
                ('Year', models.IntegerField()),
                ('Description', models.TextField()),
                ('Language', models.CharField(max_length=100)),
            ],
        ),
    ]
