# Generated by Django 4.2.6 on 2024-04-26 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_pk', models.IntegerField()),
                ('count', models.IntegerField()),
                ('product_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.books')),
            ],
        ),
    ]
