# Generated by Django 4.2.6 on 2024-04-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='Author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='Language',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='Pages',
            new_name='pages',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='Stock',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='Year',
            new_name='year',
        ),
        migrations.AddField(
            model_name='books',
            name='country',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
