# Generated by Django 4.2.6 on 2024-05-10 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_adresses_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adresses',
            new_name='Addresses',
        ),
    ]
