# Generated by Django 4.2.6 on 2024-05-17 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_adresses_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_pk',
            field=models.ForeignKey(db_column='product_pk', on_delete=django.db.models.deletion.CASCADE, to='backend.books'),
        ),
    ]
