# Generated by Django 4.2.6 on 2024-05-24 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_cart_product_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user_pk',
            field=models.ForeignKey(db_column='user_pk', on_delete=django.db.models.deletion.CASCADE, to='backend.users'),
        ),
    ]
